//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpamTools.lib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int Id { get; set; }
        public string Adress { get; set; }
        public int Port { get; set; }
        public bool UseSSL { get; set; }
    
        public virtual SchedulerTasks SchedulerTasks { get; set; }
    }
}
