//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpamTools.lib.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpamDBContainer : DbContext
    {
        public SpamDBContainer()
            : base("name=SpamDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailRecipient> EmailRecipientSet { get; set; }
        public virtual DbSet<EmailSender> EmailSenderSet { get; set; }
        public virtual DbSet<Server> ServerSet { get; set; }
        public virtual DbSet<Email> EmailSet { get; set; }
        public virtual DbSet<SchedulerTasks> SchedulerTasksSet { get; set; }
        public virtual DbSet<EmailList> EmailListSet { get; set; }
    }
}
